# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='tool_icons/')),
                ('favorite', models.BooleanField(default=False)),
                ('work_related', models.BooleanField(default=False)),
            ],
        ),
    ]
