# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyc_wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifispot',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wifispot',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
