# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyc_wifi', '0002_auto_20171030_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifispot',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
